name = "GLPK"
uuid = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
repo = "https://github.com/JuliaOpt/GLPK.jl.git"
version = "0.9.1"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
LinQuadOptInterface = "f8899e07-120b-5979-ab1d-7b97bb9e1a48"

[compat]
BinaryProvider = "≥ 0.3.0"
LinQuadOptInterface = "0.6"
julia = "1"
